version: "3.9"
services:
  weather-service:
    build: .
    image: weather-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: weather-service
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-telemetry}
      MONGODB_COLLECTION_LOGS: ${MONGODB_COLLECTION_LOGS:-logs}
      MONGODB_COLLECTION_TRACES: ${MONGODB_COLLECTION_TRACES:-traces}
      MONGODB_COLLECTION_METRICS: ${MONGODB_COLLECTION_METRICS:-metrics}
      MONGODB_METRICS_EXPORT_INTERVAL: ${MONGODB_METRICS_EXPORT_INTERVAL:-PT30S}
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-http://otel-collector:4318/v1/traces}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:-http://otel-collector:4318/v1/metrics}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-none}
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  otel-collector:
    image: otel/opentelemetry-collector:0.94.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
volumes:
  mongo-data:
