version: "3.9"
services:
  weather-service:
    build: .
    image: weather-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  otel-collector:
    image: otel/opentelemetry-collector:0.94.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
volumes:
  mongo-data:
